button0_key=LEFT
button0_label=Vľavo
button1_key=DOWN
button1_label=Dole
button2_key=UP
button2_label=Otočiť
button3_key=RIGHT
button3_label=Vpravo
button4_key=-
button4_label=nepoužité
button5_key=-
button5_label=nepoužité
button6_key=-
button6_label=nepoužité
button7_key=-
button7_label=nepoužité
button8_key=ENTER
button8_label=Pauza / potvrdenie
