button0_key=A
button0_label=Vyšší prevod
button1_key=-
button1_label=nepoužité
button2_key=RIGHT
button2_label=Riadenie vpravo
button3_key=DOWN
button3_label=Brzda
button4_key=Z
button4_label=Nižší prevod
button5_key=-
button5_label=nepoužité
button6_key=LEFT
button6_label=Riadenie vľavo
button7_key=UP
button7_label=Plyn
button8_key=SPACE
button8_label=Štart / potvrdenie
