name=Grand Prix Circuit: Cycles
data_dir=grand-prix-cycles
exe=GPEGA.EXE
dosbox_conf=dosbox.conf
mapper_file=mapper.txt
ddr_file=ddr.conf
asset_archive=/home/dietpi/pi-286-game-assets/grand-prix-circuit-cycles.zip
