input_profile=prehistorik_mat
pregame_keyboard=Šípky: pohyb; SPACE: skok.|F1: späť do menu.
pregame_pad=↑ pohyb hore; ↖/↗ diagonálne hore; ↓ pohyb dole.|↙, ↘ a START: skok.|SELECT: späť do menu.
pregame_both=Šípky pohyb, SPACE skok.|Podložka: ↖/↗ diagonálne hore; ↙, ↘ a START skok.|F1 alebo SELECT: späť do menu.
button0_key=LEFT
button0_label=Chôdza vľavo
button1_key=DOWN
button1_label=Drep
button2_key=UP
button2_label=Skok
button3_key=RIGHT
button3_label=Chôdza vpravo
button4_key=SPACE
button4_label=Skok
button5_key=SPACE
button5_label=Skok
button6_key=UP
button6_label=Hore vľavo
button7_key=UP
button7_label=Hore vpravo
button8_key=SPACE
button8_label=Skok
